name: Bug Report
description: Report bugs you've found here so we can continue to improve!
title: "BUG: "
type: bug
projects: ["CRB-GDI/42"]

body:
  - type: markdown
    attributes:
      value: "## Provide the details below."

  - type: textarea
    id: what-happened
    attributes:
      label: "What happened?"
      description: "A clear and concise description of what the bug is"
      placeholder: "ex. Player health display does not change when taking damage."

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: "How can we reproduce the issue?"
      description: "Provide detailed steps to reproduce the behavior"
      placeholder: 
      "## Steps
      1 In level 1 I encountered the red range enemy by the first obstacle.  UI displayed health of 10
      2 Range enemy attack made contact with the player
      3 Health UI display remained at 10."
      render: markdown
