name: "Bug Report (form)"
description: "Report the bugs you find so we can continue to improve!"
title: "BUG: "
type: Bug
projects: ["CRB-GDI/42"]

body:
  - type: markdown
    attributes:
      value: "## Provide the bug details below"

  - type: textarea
    id: what-happened
    attributes:
      label: "What happened?"
      description: "Provide a clear and concise description of what the bug is."
      placeholder: "ex. Player health does not change when taking damage"

  - type: textarea
    id: reproduce
    attributes:
      label: "How to reproduce the issue?"
      description: "Provide detailed steps to reproduce the behavior."
      value: "1. Do this. ... 
      2. Then do that. ... 
      3. Then do the other."
      render: markdown
