name: Bug Report
description: Report bugs you've found here so we can continue to improve!
title: "BUG: "
type: bug
projects: ["CRB-GDI/42"]

body:
  - type: markdown
    attributes:
      value: "Tell us what you saw."
