name: Bug Report
description: Report bugs you've found here so we can continue to improve!
title: "BUG: "
type: bug
projects: ["CRB-GDI/42"]

body:
  - type: markdown
    attributes:
      value: "## Provide the details below."

  - type: textarea
    id: what-happened
    attributes:
      label: "What happened?"
      description: "A clear and concise description of what the bug is"
      placeholder: "ex. Player health display does not change when taking damage."
