name: "Task Item"
description: "Add an artist or programmer's task to the project."
title: "TO DO: "

body:
  - type: markdown
    attributes:
      value: "Provide the task details below."
 
  - type: dropdown
    id: taskType
    attributes:
      label: "Task type"
      options:
        - "(Design) UI Wireframe"
        - "(Design) Dialogue Script"
        - "(Programming) Scene"
        - "(Programming) Prefab"
        - "(Programming) Animation Controller"
        - "(Programming) Script"
        - "(Art) Button Image"
        - "(Art) Icon Image"
        - "(Art) Animation Clips"
        - "(Art) Character"
        - "(Art) Environment"
        - "(Sound) Voice Over"
        - "(Sound) SFX"
        - "(Sound) Ambient"
    validations:
      required: true
  - type: dropdown
    id: taskEffort
    attributes:
      label: "What is the estimated effort for this task?"
      options:
      - Unknown (Default)
      - Low
      - Medium
      - High
      - Huge
    validations:
      required: true
  - type: dropdown
    id: taskPriority
    attributes:
      label: "What is the priority for this task?"
      options:
        - Undefined (Default)
        - Must
        - Should
        - Could
        - Wont
