name: Task Item
description: Add a Task to the To Do List.
title: "[Task]: "

body:
  - type: markdown
    attributes:
      value: |
        Provide the details for the new task below.
  - type: input
    id: taskDesc
    attributes:
      label: Task Description
      description: Provide a brief description of the task (50 char max).
      placeholder: ex. Create player movement script

  - type: dropdown
    id: taskType
    attributes:
      label: Task Type
      description: Select the task type.
      options:
        - Art
        - Design
        - Programming
        - Sound

   - type: dropdown
    id: effort
    attributes:
      label: Effort
      description: What is the estimated effort level for this task. 
      options:
        - Low (less than 1 class period)
        - Med (1 - 2 class periods)
        - High (3 - 4 class periods)
        - Huge (More than 4 class periods)

  - type: dropdown
    id: priority
    attributes:
      label: What is the priority of this task?
      options:
      - 1 Must Have
      - 2 Should Have
      - 3 Could Have
      - 4 Won't Have
   
