name: "User Story"
description: "Add an artist or programmer's task to the project."
title: "Story: "
type: Task
projects: ["CRB-GDI/42"]

body:
  - type: markdown
    attributes:
      value: "Provide the user story details below."
  
  - type: input
    id: storyName
    attributes:
      label: "Story Title "
      description: "Provide a brief title for this user story"
      placeholder: "ex. "
            
  - type: input
    id: userType
    attributes:
      label: "As a..."
      description: "Provide the WHO, what type of user?"
      placeholder: "ex. mobile app user" 
    validations:
      required: true

  - type: input
    id: what
    attributes:
      label: "I want to..."
      description: "Complete the phrase to describe what the user will see without getting bogged down in implementation details"
      placeholder: "ex. save all my data to the cloud"

  - type: input
    id: why
    attributes:
      label: "So I can..."
      description: "Complete the phrase explaining why this is important to the user"
      placeholder: "ex. access it from another device"

  - type: markdown
    attributes:
      value: "Validation test (optional)"
  - type: input
    attributes:
      label: "When I … (action)"
      description: "Provide the test scenario, user behavior"
      placeholder: "ex. "
      
  - type: input
    attributes:
      label: "This happens … (outcome)"
      description: "Provide the expected result or outcome when that scenario executes or the user does the behavior"
      placeholder: "ex. "
